service: test-lambda
variablesResolutionMode: 20210326
frameworkVersion: '2'

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    packager: 'yarn'
    packagerOptions:
      scripts:
        - npx prisma generate
    includeModules: true
      # nodeModulesRelativeDir: '../../'
      # forceInclude:
      #   - "@prisma/client"
      #   - ".bin"
      #   - ".prisma"
      # forceExclude:
      #   - ".prisma"

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x

  stage: ${opt:stage, 'staging'}
  region: eu-west-1

functions:
  helloHandler:
    handler: src/hello.handler