service: lambda-one
variablesResolutionMode: 20210326
frameworkVersion: '2'

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    packager: 'yarn'
    packagerOptions:
      scripts:
        - npx prisma generate
    includeModules:
      nodeModulesRelativeDir: '../../../'

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  helloHandler:
    handler: src/hello.handler