service: id-lambda
variablesResolutionMode: 20210326
frameworkVersion: "2"

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "yarn"
    packagerOptions:
      scripts:
        - npx prisma generate
    includeModules: true
    # Don't include the Darwin query engine generated for macOS
    excludeRegex: "query-engine-darwin"

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x

  stage: ${opt:stage, 'staging'}
  region: eu-west-1

  environment:
    DATABASE_URL: your-db-url
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  idHandler:
    handler: src/handler.handler
    events:
      - http:
          method: GET
          path: /
